baseurl = "http://maartentamboer.github.io/docs/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-learn"
canonifyurls = true

[params]
  editURL = "https://github.com/Open-Canalyzer/docs"
  description = "Documentation for the Open-Canalyzer"
  author = "Maarten Tamboer and Jerry Jacobs"
